### ISSUE TITLE
Resto del curso

### ISSUE THREAD

**Issue by pprietosdi** [idu-bogota/curso-taller-openerp#5]
Hola!

Antes de nada felicitarte por el fabuloso curso sobre Odoo. Llevaba tiempo buscando algo sencillo y concreto y el curso que has subido es realmente bueno. Sin embargo, he visto que faltan algunas lecciones y me gustaría realizar el curso completo. ¿Tienes intención de subir el resto de temas que faltan?

Gracias por adelantado

**Comment by cinxgler** [comment]
Hola,

Grracias por tu interes, estoy pendiente de hacer algunas nuevas lecciones en estas semanas.

**Comment by jorgereed** [comment]
Muchas gracias. Se agradece tanto trabajo. Estaré esperándolo. Un saludo

**Comment by pprietosdi** [comment]
Muchas gracias. Se agradece tanto trabajo. Estaré esperándolo. Un saludo
